environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - cmd: SET PATH=C:\Users\appveyor\.m2\apache-maven-3.5.4-bin\4lcg54ki11c6mp435njk296gm5\apache-maven-3.5.4\bin;%JAVA_HOME%\bin;%PATH%

build_script:
  - .\mvnw.cmd clean verify

cache:
  - C:\Users\appveyor\.m2\repository
  - C:\Users\appveyor\.m2\wrapper
